/* ============================================================
   NTell World Ink — site index page
   site-index.js  ·  no dependencies, no build step

   Renders /search-index.json as one filterable list. The index is
   generated by tools/build-index.js; see tools/README.md.

   The list is drawn in the browser rather than written into the
   HTML, which is what keeps the client-area rows out of reach of
   crawlers: robots.txt disallows /search-index.json, so a crawler
   that honours it never sees the data to render.
   ============================================================ */

(function () {
  'use strict';

  var INDEX_URL = '/search-index.json';

  // Chip order, and the type each chip filters to.
  var CHIPS = ['Everything', 'Course', 'Lesson', 'Workshop', 'Presentation', 'Simulation', 'Resource', 'Client'];

  // Group order is fixed. Empty groups are omitted at render time.
  var GROUPS = [
    { name: 'Courses and lessons', types: ['Course', 'Lesson'] },
    { name: 'Workshops', types: ['Workshop'] },
    { name: 'Presentations', types: ['Presentation'] },
    { name: 'Simulation tools', types: ['Simulation'] },
    { name: 'Resources', types: ['Resource'] },
    { name: 'Client areas (hidden)', types: ['Client'] },
  ];

  var elQuery = document.getElementById('si-q');
  var elChips = document.getElementById('si-chips');
  var elCount = document.getElementById('si-count');
  var elList = document.getElementById('si-list');
  var elTotal = document.getElementById('si-total');

  var index = [];
  var typeFilter = 'Everything';

  /* --- Helpers --------------------------------------------- */

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function plural(n, word) {
    return n + ' ' + word + (n === 1 ? '' : 's');
  }

  /* --- Filtering -------------------------------------------
     Same rule as the header search: every whitespace-separated
     token must appear somewhere in title, section, topic or url.
     ---------------------------------------------------------- */

  function filtered() {
    var tokens = (elQuery.value || '').toLowerCase().split(/\s+/).filter(Boolean);
    return index.filter(function (e) {
      if (typeFilter !== 'Everything' && e.type !== typeFilter) return false;
      for (var i = 0; i < tokens.length; i++) {
        if (e._blob.indexOf(tokens[i]) === -1) return false;
      }
      return true;
    });
  }

  /* --- Rendering -------------------------------------------- */

  function rowHtml(e) {
    return '<a class="si-row" href="' + escapeHtml(e.url) + '"' +
      (e.hidden ? ' rel="nofollow"' : '') + '>' +
        '<span class="si-row-title">' + escapeHtml(e.title) + '</span>' +
        '<span class="si-row-url">' + escapeHtml(e.url) + '</span>' +
        '<span class="idx-pills">' +
          '<span class="idx-pill">' + escapeHtml(e.type) + '</span>' +
          (e.hidden ? '<span class="idx-pill idx-pill-hidden" title="Kept out of search engines">&#9679;</span>' : '') +
        '</span>' +
      '</a>';
  }

  function render() {
    var rows = filtered();

    elCount.textContent = rows.length + ' of ' + plural(index.length, 'page') + ' shown';

    if (!rows.length) {
      elList.innerHTML = '<p class="si-empty">No page matches that. Try fewer words, ' +
        'or set the type filter back to Everything.</p>';
      return;
    }

    var html = '';
    GROUPS.forEach(function (group) {
      var inGroup = rows.filter(function (e) { return group.types.indexOf(e.type) !== -1; });
      if (!inGroup.length) return;
      inGroup.sort(function (a, b) { return a.title.localeCompare(b.title); });

      html += '<section class="si-group">' +
        '<div class="si-group-head">' +
          '<h2>' + escapeHtml(group.name) + '</h2>' +
          '<span class="si-group-rule"></span>' +
          '<span class="si-group-count">' + plural(inGroup.length, 'page') + '</span>' +
        '</div>' +
        inGroup.map(rowHtml).join('') +
        '</section>';
    });
    elList.innerHTML = html;
  }

  /* --- Chips ------------------------------------------------ */

  function buildChips() {
    elChips.innerHTML = CHIPS.map(function (name) {
      return '<button type="button" class="si-chip" data-type="' + escapeHtml(name) + '"' +
        ' aria-pressed="' + (name === typeFilter) + '">' + escapeHtml(name) + '</button>';
    }).join('');
  }

  elChips.addEventListener('click', function (e) {
    var chip = e.target.closest('.si-chip');
    if (!chip) return;
    typeFilter = chip.getAttribute('data-type');
    Array.prototype.forEach.call(elChips.querySelectorAll('.si-chip'), function (c) {
      c.setAttribute('aria-pressed', String(c === chip));
    });
    render();
    syncUrl();
  });

  /* --- Query string ----------------------------------------- */

  function seedFromUrl() {
    var params = new URLSearchParams(window.location.search);
    var q = params.get('q');
    if (q) elQuery.value = q;
    var t = params.get('type');
    if (t && CHIPS.indexOf(t) !== -1) typeFilter = t;
  }

  function syncUrl() {
    var params = new URLSearchParams();
    if (elQuery.value.trim()) params.set('q', elQuery.value.trim());
    if (typeFilter !== 'Everything') params.set('type', typeFilter);
    var search = params.toString();
    history.replaceState(null, '', search ? '?' + search : window.location.pathname);
  }

  var timer = null;
  elQuery.addEventListener('input', function () {
    clearTimeout(timer);
    timer = setTimeout(function () { render(); syncUrl(); }, 120);
  });

  /* --- Load -------------------------------------------------- */

  seedFromUrl();
  buildChips();

  fetch(INDEX_URL)
    .then(function (r) {
      if (!r.ok) throw new Error('search index ' + r.status);
      return r.json();
    })
    .then(function (data) {
      index = data.map(function (e) {
        e._blob = (e.title + ' ' + e.section + ' ' + (e.topic || '') + ' ' + e.url).toLowerCase();
        return e;
      });
      elTotal.textContent = index.length;
      render();
      if (elQuery.value) elQuery.focus();
    })
    .catch(function () {
      elCount.textContent = '';
      elList.innerHTML = '<p class="si-empty">The index could not be loaded just now. ' +
        'Reload the page, or use the navigation above.</p>';
    });
})();
