/* ============================================================
   NTell World Ink — site search
   search.js  ·  no dependencies, no build step

   Injects a search field and filters /search-index.json in the
   browser. The index is generated by tools/build-index.js; see
   tools/README.md.

   Mount point: if the page carries an element with id
   "site-search-mount" the field goes there (the home page puts it in
   the banner, under the masthead). Otherwise it goes into
   header.site, which is where every inner page keeps it.

   Client-area pages appear in results and are marked with a
   "hidden" pill. They stay out of sitemap.xml and out of search
   engines through their own noindex tags.
   ============================================================ */

(function () {
  'use strict';

  var INDEX_URL = '/search-index.json';
  var INDEX_PAGE = '/index/';
  var MAX_RESULTS = 8;      // anything beyond this goes to the index page
  var DEBOUNCE_MS = 120;

  var mount = document.getElementById('site-search-mount');
  var header = document.querySelector('header.site');
  var host = mount || (header && header.querySelector('.site-inner'));
  if (!host) return;                                   // nowhere to put the field
  if (document.querySelector('.site-search')) return;  // already present

  /* --- Build the field ------------------------------------ */

  var wrap = document.createElement('div');
  wrap.className = 'site-search';
  wrap.innerHTML =
    '<svg class="site-search-icon" viewBox="0 0 16 16" aria-hidden="true">' +
      '<circle cx="7" cy="7" r="5"></circle><path d="m11 11 4 4"></path>' +
    '</svg>' +
    '<input class="site-search-input" type="search" autocomplete="off" spellcheck="false"' +
    ' placeholder="Search the whole site" aria-label="Search the whole site"' +
    ' role="combobox" aria-expanded="false" aria-autocomplete="list"' +
    ' aria-controls="site-search-results">' +
    '<span class="site-search-key" aria-hidden="true">/</span>';
  host.appendChild(wrap);

  var panel = document.createElement('div');
  panel.className = 'site-search-panel';
  panel.hidden = true;
  (mount || header).appendChild(panel);

  var input = wrap.querySelector('.site-search-input');

  /* --- Data ------------------------------------------------ */

  var index = null;
  var loading = null;

  function load() {
    if (index) return Promise.resolve(index);
    if (loading) return loading;
    loading = fetch(INDEX_URL)
      .then(function (r) {
        if (!r.ok) throw new Error('search index ' + r.status);
        return r.json();
      })
      .then(function (data) {
        index = data.map(function (e) {
          e._blob = (e.title + ' ' + e.section + ' ' + (e.topic || '') + ' ' + e.url).toLowerCase();
          return e;
        });
        window.__ntwiSearchIndex = index;
        return index;
      })
      .catch(function (err) {
        loading = null;
        throw err;
      });
    return loading;
  }

  /* --- Matching --------------------------------------------
     Every whitespace-separated token must appear as a substring
     of title + section + topic + url. Substring, not fuzzy: fuzzy
     matching produced false positives during review.
     ---------------------------------------------------------- */

  function search(query) {
    var tokens = query.toLowerCase().split(/\s+/).filter(Boolean);
    if (!tokens.length || !index) return [];
    var hits = index.filter(function (e) {
      for (var i = 0; i < tokens.length; i++) {
        if (e._blob.indexOf(tokens[i]) === -1) return false;
      }
      return true;
    });
    // A title match beats a match buried in the section or the URL.
    var first = tokens[0];
    hits.sort(function (a, b) {
      return rank(a, first) - rank(b, first) || a.title.localeCompare(b.title);
    });
    return hits;
  }

  function rank(entry, token) {
    var title = entry.title.toLowerCase();
    if (title.indexOf(token) === 0) return 0;
    if (title.indexOf(token) !== -1) return 1;
    return 2;
  }

  /* --- Rendering ------------------------------------------- */

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function render(query, hits) {
    var shown = hits.slice(0, MAX_RESULTS);
    var html = '';

    html += '<div class="site-search-head">' +
      (hits.length === 1 ? '1 result across the site' : hits.length + ' results across the site') +
      '</div>';

    if (!hits.length) {
      html += '<div class="site-search-empty">Nothing matches those words. Try fewer of them, ' +
        'or open the site index for the full list.</div>';
    } else {
      html += '<ul class="site-search-results" id="site-search-results" role="listbox">';
      shown.forEach(function (e, i) {
        html += '<li role="presentation">' +
          '<a class="site-search-result" role="option" id="site-search-opt-' + i + '"' +
          ' aria-selected="false" href="' + escapeHtml(e.url) + '"' +
          (e.hidden ? ' rel="nofollow"' : '') + '>' +
            '<span class="site-search-result-main">' +
              '<span class="site-search-result-title">' + escapeHtml(e.title) + '</span>' +
              '<span class="site-search-result-url">' + escapeHtml(e.url) + '</span>' +
            '</span>' +
            '<span class="idx-pills">' +
              '<span class="idx-pill">' + escapeHtml(e.type) + '</span>' +
              (e.hidden ? '<span class="idx-pill idx-pill-hidden">&#9679; hidden</span>' : '') +
            '</span>' +
          '</a></li>';
      });
      html += '</ul>';
    }

    html += '<a class="site-search-foot" href="' + INDEX_PAGE + '?q=' +
      encodeURIComponent(query) + '">See all results in the site index &rarr;</a>';

    panel.innerHTML = html;
    open();
    setActive(-1);
  }

  /* --- Open, close, highlight ------------------------------ */

  var active = -1;

  function options() {
    return Array.prototype.slice.call(panel.querySelectorAll('.site-search-result'));
  }

  function open() {
    panel.hidden = false;
    wrap.classList.add('is-open');
    input.setAttribute('aria-expanded', 'true');
  }

  function close() {
    panel.hidden = true;
    wrap.classList.remove('is-open');
    input.setAttribute('aria-expanded', 'false');
    input.removeAttribute('aria-activedescendant');
    active = -1;
  }

  function setActive(i) {
    var opts = options();
    opts.forEach(function (el) {
      el.classList.remove('is-active');
      el.setAttribute('aria-selected', 'false');
    });
    active = i;
    if (i < 0 || !opts[i]) {
      input.removeAttribute('aria-activedescendant');
      return;
    }
    opts[i].classList.add('is-active');
    opts[i].setAttribute('aria-selected', 'true');
    input.setAttribute('aria-activedescendant', opts[i].id);
    opts[i].scrollIntoView({ block: 'nearest' });
  }

  function move(step) {
    var opts = options();
    if (!opts.length) return;
    var next = active + step;
    if (next < 0) next = opts.length - 1;
    if (next >= opts.length) next = 0;
    setActive(next);
  }

  /* --- Wiring ---------------------------------------------- */

  var timer = null;

  function run() {
    var query = input.value.trim();
    if (!query) { close(); return; }
    load().then(function () {
      if (input.value.trim() !== query) return;   // a later keystroke won
      render(query, search(query));
    }).catch(function () {
      panel.innerHTML = '<div class="site-search-empty">Search is unavailable just now. ' +
        'The site index still works.</div>' +
        '<a class="site-search-foot" href="' + INDEX_PAGE + '">Open the site index &rarr;</a>';
      open();
    });
  }

  input.addEventListener('input', function () {
    clearTimeout(timer);
    timer = setTimeout(run, DEBOUNCE_MS);
  });

  input.addEventListener('focus', function () { load().catch(function () {}); });

  input.addEventListener('keydown', function (e) {
    if (e.key === 'ArrowDown') { e.preventDefault(); move(1); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); move(-1); }
    else if (e.key === 'Enter') {
      var opts = options();
      var target = opts[active] || opts[0];
      if (target) { e.preventDefault(); window.location.href = target.href; }
    } else if (e.key === 'Escape') {
      input.value = '';
      close();
      input.blur();
    }
  });

  // "/" focuses the field from anywhere on the page.
  document.addEventListener('keydown', function (e) {
    if (e.key !== '/' || e.metaKey || e.ctrlKey || e.altKey) return;
    var el = document.activeElement;
    if (el && (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' ||
               el.tagName === 'SELECT' || el.isContentEditable)) return;
    e.preventDefault();
    input.focus();
    input.select();
  });

  document.addEventListener('click', function (e) {
    if (!panel.hidden && !panel.contains(e.target) && !wrap.contains(e.target)) close();
  });
})();
