#!/usr/bin/env node
'use strict';

/**
 * add-meta.js
 * ---------------------------------------------------------------------------
 * Writes the social preview tags and the icon links into every page's <head>.
 *
 * Each page gets Open Graph and Twitter card tags, a canonical URL, the icon
 * links and a theme colour, wrapped in a marked block:
 *
 *   <!-- social: generated by tools/add-meta.js; edit the script, not this -->
 *   ...
 *   <!-- /social -->
 *
 * Re-running replaces that block, so titles and descriptions stay in step with
 * the pages. Titles come from search-index.json where the page is listed, which
 * means any hand-set title in tools/index-meta.json is used here too; pages not
 * in the index fall back to their own <title>.
 *
 *   node tools/add-meta.js            apply
 *   node tools/add-meta.js --dry-run  report only
 * ---------------------------------------------------------------------------
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

const ORIGIN = (function () {
  try {
    return 'https://' + fs.readFileSync(path.join(ROOT, 'CNAME'), 'utf8').trim();
  } catch (e) {
    return 'https://ntworldink.com';
  }
})();

const SITE_NAME = 'NT World Ink';
const CARD = '/assets/brand/ntwi-social-card.png';
const CARD_ALT = 'ntworld.ink. Learning materials in cybersecurity, AI literacy, ' +
  'Microsoft Office and workplace digital skills.';
const DEFAULT_DESCRIPTION = 'Practical learning materials in cybersecurity, AI literacy, ' +
  'Microsoft Office and workplace digital skills. Real datasets; real exercises; ' +
  'everything downloadable and yours to keep.';

// Kept in step with tools/build-index.js, so the same pages are covered.
const SKIP_DIRS = new Set([
  '.git',
  '_to_delete',
  'digitalliteracy',   // legacy Tennant Creek path; duplicates /digital-literacy/
  'node_modules',
  'assets',
]);

const SKIP_PATTERNS = [
  /-original\.html$/,  // superseded Roper Gulf drafts
];

// Redirect stubs. They carry their own canonical pointing at the page they
// redirect to, and a second, self-referring canonical would fight it.
const SKIP_URLS = new Set([
  '/resources/websites-and-tools.html',
  '/resources/articles-and-papers.html',
]);

const OPEN = '<!-- social: generated by tools/add-meta.js; edit the script, not this -->';
const CLOSE = '<!-- /social -->';

const ENTITIES = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ',
  middot: '·', mdash: '—', ndash: '–', hellip: '…',
  rsquo: '’', lsquo: '‘', ldquo: '“', rdquo: '”',
};

function decodeEntities(s) {
  return s
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(parseInt(d, 10)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCharCode(parseInt(h, 16)))
    .replace(/&([a-z]+);/gi, (m, name) => {
      const key = name.toLowerCase();
      return Object.prototype.hasOwnProperty.call(ENTITIES, key) ? ENTITIES[key] : m;
    });
}

function attr(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function walk(dir, out) {
  out = out || [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(full, out);
    } else if (entry.isFile() && entry.name.toLowerCase().endsWith('.html')) {
      out.push(full);
    }
  }
  return out;
}

function toUrl(relPath) {
  const p = relPath.split(path.sep).join('/');
  if (p === 'index.html') return '/';
  if (p.endsWith('/index.html')) return '/' + p.slice(0, -'index.html'.length);
  return '/' + p;
}

/** Fallback title cleaner for pages the index does not list. */
function cleanTitle(raw) {
  const parts = raw.split(/\s*[·—–]\s*/).map((s) => s.trim()).filter(Boolean);
  if (parts.length < 2) return raw;
  const last = parts[parts.length - 1].toLowerCase();
  if (last === 'ntell world ink' || last === 'nt world ink') parts.pop();
  return parts.join(', ');
}

function block(page) {
  const lines = [
    OPEN,
    `<link rel="canonical" href="${attr(ORIGIN + page.url)}">`,
    `<meta property="og:type" content="${page.type}">`,
    `<meta property="og:site_name" content="${attr(SITE_NAME)}">`,
    `<meta property="og:locale" content="en_AU">`,
    `<meta property="og:title" content="${attr(page.title)}">`,
    `<meta property="og:description" content="${attr(page.description)}">`,
    `<meta property="og:url" content="${attr(ORIGIN + page.url)}">`,
    `<meta property="og:image" content="${attr(ORIGIN + CARD)}">`,
    `<meta property="og:image:width" content="1200">`,
    `<meta property="og:image:height" content="630">`,
    `<meta property="og:image:alt" content="${attr(CARD_ALT)}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    `<meta name="twitter:title" content="${attr(page.title)}">`,
    `<meta name="twitter:description" content="${attr(page.description)}">`,
    `<meta name="twitter:image" content="${attr(ORIGIN + CARD)}">`,
    `<meta name="twitter:image:alt" content="${attr(CARD_ALT)}">`,
    `<link rel="icon" href="/favicon.svg" type="image/svg+xml">`,
    `<link rel="icon" href="/favicon-32.png" sizes="32x32" type="image/png">`,
    `<link rel="apple-touch-icon" href="/apple-touch-icon.png">`,
    `<meta name="theme-color" content="#0a0a0c">`,
    CLOSE,
  ];
  return lines.join('\n');
}

function main() {
  const dryRun = process.argv.includes('--dry-run');

  let indexByUrl = {};
  try {
    JSON.parse(fs.readFileSync(path.join(ROOT, 'search-index.json'), 'utf8'))
      .forEach(function (e) { indexByUrl[e.url] = e; });
  } catch (e) {
    console.log('note: search-index.json not readable; falling back to page titles');
  }

  const files = walk(ROOT);
  let written = 0;
  let refreshed = 0;
  let removed = 0;
  const noDescription = [];
  const noTitle = [];

  for (const file of files) {
    const rel = path.relative(ROOT, file);
    if (SKIP_PATTERNS.some((re) => re.test(rel))) continue;

    const url = toUrl(rel);
    let html = fs.readFileSync(file, 'utf8');

    if (!/<head[^>]*>/i.test(html)) continue;

    const marker = new RegExp('\\n?' + OPEN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
      '[\\s\\S]*?' + CLOSE.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));

    // A page that should not carry the block, and once did, gets it taken back out.
    if (SKIP_URLS.has(url)) {
      if (marker.test(html)) {
        removed++;
        if (!dryRun) fs.writeFileSync(file, html.replace(marker, ''));
      }
      continue;
    }

    const titleMatch = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
    const rawTitle = titleMatch ? decodeEntities(titleMatch[1]).replace(/\s+/g, ' ').trim() : '';
    if (!rawTitle) noTitle.push(url);

    const entry = indexByUrl[url];
    const title = (entry && entry.title) || cleanTitle(rawTitle) || SITE_NAME;

    // Read the page's own description, ignoring anything inside our own block.
    const outside = html.replace(new RegExp(OPEN + '[\\s\\S]*?' + CLOSE), '');
    const descMatch = outside.match(/<meta\s+name=["']description["']\s+content=["']([\s\S]*?)["']\s*\/?>/i);
    const description = descMatch
      ? decodeEntities(descMatch[1]).replace(/\s+/g, ' ').trim()
      : DEFAULT_DESCRIPTION;
    if (!descMatch) noDescription.push(url);

    const ogType = url === '/' ? 'website' : 'article';

    const next = block({ url, title, description, type: ogType });

    let updated;
    if (marker.test(html)) {
      updated = html.replace(marker, '\n' + next);
      if (updated !== html) refreshed++;
    } else {
      // Insert after the viewport meta where there is one, otherwise after <head>.
      const viewport = html.match(/[^\S\n]*<meta\s+name=["']viewport["'][^>]*>/i);
      if (viewport) {
        updated = html.replace(viewport[0], viewport[0] + '\n' + next);
      } else {
        updated = html.replace(/(<head[^>]*>)/i, '$1\n' + next);
      }
      written++;
    }

    if (updated !== html && !dryRun) fs.writeFileSync(file, updated);
  }

  console.log((dryRun ? 'would add ' : 'added ') + written + ' new block' + (written === 1 ? '' : 's') +
    ', ' + (dryRun ? 'would refresh ' : 'refreshed ') + refreshed +
    (removed ? ', ' + (dryRun ? 'would remove ' : 'removed ') + removed : ''));

  if (noDescription.length) {
    console.log('');
    console.log('No meta description, so the site default was used (' + noDescription.length + '):');
    for (const u of noDescription) console.log('  ' + u);
  }
  if (noTitle.length) {
    console.log('');
    console.log('No <title> (' + noTitle.length + '):');
    for (const u of noTitle) console.log('  ' + u);
  }
}

main();
